version: "3.9"
services:

  server:
    build:
      dockerfile: app.server.Dockerfile
      context: .
    restart: always
    environment:
      - SERVER_ADDRESS=:8080

  client:
    build:
      dockerfile: app.client.Dockerfile
      context: .
    restart: always
    depends_on:
      - server
    environment:
      - SERVER_ADDRESS=server:8080